[package]
name = "advent-of-code-2022"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
ureq = "2.5.0"

[dev-dependencies.cargo-husky]
version = "1"
features = ["precommit-hook", "run-cargo-test", "run-cargo-clippy"]
